credentials:
  usernames:
    jherth:
      email: johann.herth@irsn.fr
      logged_in: False # Will be managed automatically
      name: Johan Herth
      password: abc # Will be hashed automatically
    rbriggs:
      email: rbriggs@gmail.com
      logged_in: False # Will be managed automatically
      name: Rebecca Briggs
      password: def # Will be hashed automatically
cookie:
  expiry_days: 0
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com